<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\build\props\Base.props"/>
    <Import Project="..\..\build\props\OneWare.Module.props"/>


    <ItemGroup>
        <ProjectReference Include="..\OneWare.Essentials\OneWare.Essentials.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.20" />
        <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="10.9.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
        <AvaloniaResource Include="Assets\TOML.tmLanguage.json"/>
    </ItemGroup>
</Project>
