<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>OneWareCLI</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.CommandLine" Version="3.0.0-rc.1.26425.128" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\OneWare.Core\OneWare.Core.csproj" />
      <ProjectReference Include="..\..\src\OneWare.CloudIntegration\OneWare.CloudIntegration.csproj" />
    </ItemGroup>

</Project>
