name: oneware
base: core24

confinement: classic

adopt-info: oneware

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

icon: ./studio/OneWare.Studio/Assets/com.one_ware.OneWare.svg

apps:
  oneware:
    command: ./OneWareStudio
    common-id: com.one_ware.OneWare
    desktop: ./com.one_ware.OneWare.desktop
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin:$PATH"

parts:
  oneware:
    plugin: dump
    source: .
    parse-info: [studio/OneWare.Studio.Desktop/com.one_ware.OneWare.metainfo.xml]
    build-packages:
      - libicu74
    override-build: |
      export TZ=Europe/Berlin
      ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 10.0
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
      export DOTNET_NOLOGO=1
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      
      # Determine the correct .NET runtime identifier based on architecture
      if [ "$SNAPCRAFT_TARGET_ARCH" = "arm64" ]; then
        DOTNET_RID="linux-arm64"
      else
        DOTNET_RID="linux-x64"
      fi
      
      cd studio/OneWare.Studio.Desktop
      dotnet publish -r $DOTNET_RID -c Release -o $SNAPCRAFT_PART_INSTALL
      chmod +x $SNAPCRAFT_PART_INSTALL/OneWareStudio
      chmod +x $SNAPCRAFT_PART_INSTALL/AsmichiChildProcessHelper

      sed -i 's|^Icon=.*$|Icon=${SNAP}/meta/gui/com.one_ware.OneWare.svg|' $SNAPCRAFT_PART_INSTALL/com.one_ware.OneWare.desktop
    stage-packages:
      - libgtk-3-0
      - libx11-6
      - libice6
      - libsm6
      - v4l-utils
      - libglib2.0-0
      - libgobject-2.0-0
      - libgio-2.0-0